version: "3.7"

services:
  ollama_chat_devcontainer:
    container_name: ollama_chat_devcontainer
    build:
      context: .
      dockerfile: .docker/python/ubuntu/Dockerfile
    tty: true
    depends_on:
      - ollama_chat 
    volumes:
      - ./:/app
    env_file:
      - .env

  ollama_chat:
    container_name: ollama_chat
    image: ollama/ollama
    tty: true
    volumes:
      - .ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
