version: "3.8"

services:
  qa_ollama_python:
    container_name: qa_ollama_python
    build:
      context: .
      dockerfile: .docker/python/ubuntu/Dockerfile
    tty: true
    depends_on:
      - qa_ollama_server 
    volumes:
      - ./:/app
    env_file:
      - .env

  qa_ollama_server:
    container_name: qa_ollama_server
    image: ollama/ollama
    volumes:
      - .ollama:/root/.ollama
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
